FROM ubuntu:latest

RUN apt-get install -y wget

RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' > /etc/apt/sources.list.d/pgdg.list
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update
RUN apt-get install -y postgresql-9.4

USER postgres

RUN /etc/init.d/postgresql start
# RUN /etc/init.d/postgresql start &&\
#    psql --command "CREATE USER clasher CREATEDB;" &&\
#    createdb -O clasher clashdb

RUN echo 'host all all 0.0.0.0/0 trust' > /etc/postgresql/9.4/main/pg_hba.conf
RUN echo 'local all all trust' >> /etc/postgresql/9.4/main/pg_hba.conf
RUN sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/9.4/main/postgresql.conf

EXPOSE 5432

VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

CMD ["/usr/lib/postgresql/9.4/bin/postgres", "-D", "/var/lib/postgresql/9.4/main", "-c", "config_file=/etc/postgresql/9.4/main/postgresql.conf"]
