FROM ubuntu:14.04

RUN apt-get install -y nginx
RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf
RUN rm /etc/nginx/sites-enabled/default
RUN chown -R www-data:www-data /var/lib/nginx

WORKDIR /etc/nginx
COPY nginx-conf sites-enabled/drawclash
CMD nginx

VOLUME /var/log/nginx

EXPOSE 80 443
